// Generated by generate-native-manifest.js.
use next_rsc::{LayoutProps, PageProps, ParamValue, Params, RenderResult, RequestData};

pub const RUST_RSC_BUILD_ID: &str = "cb7d7a8038ecedc5";
pub const RUST_RSC_FLIGHT_REVISION: &str = "19.3.0-canary-cbb046ab-20260731";
pub const RUST_RSC_BASE_PATH: &str = "";
pub const RUST_RSC_TRAILING_SLASH: bool = false;
pub const RUST_RSC_LOCALES: &[&str] = &[];
pub const RUST_RSC_REWRITES: &[(&str, &str, bool)] = &[
    ("/native-rust-page", "/rust-page", false),
    ("/native-blog/:slug", "/blog/:slug", false),
    ("/conditional-rust", "/rust-page", true),
    ("/external-docs/:path*", "https://example.com/:path*", true),
];
pub const RUST_RSC_METADATA_TITLE: &str = "RustWorks Supply";
pub const RUST_RSC_METADATA_DESCRIPTION: &str = "A native Rust Server Components catalog";
pub const RUST_RSC_METADATA_APPLICATION_NAME: &str = "RustWorks";
pub const RUST_RSC_METADATA_GENERATOR: &str = "next-rsc";
pub const RUST_RSC_METADATA_REFERRER: &str = "origin";
pub const RUST_RSC_METADATA_CREATOR: &str = "RustWorks";
pub const RUST_RSC_METADATA_PUBLISHER: &str = "Next.js Labs";
pub const RUST_RSC_METADATA_CATEGORY: &str = "technology";
pub const RUST_RSC_WEBPACK_ASSET: &str = "/_next/static/chunks/webpack-605086c493bc8ccd.js";
pub const RUST_RSC_MAIN_ASSETS: &[&str] = &["/_next/static/chunks/main-app-b025aa0bd74a79df.js"];
pub const RUST_RSC_POLYFILL_ASSETS: &[&str] =
    &["/_next/static/chunks/polyfills-42372ed130431b0a.js"];
pub const RUST_RSC_CSS_ASSETS: &[&str] = &["/_next/static/css/9192fece8fe7c839.css"];
pub const RUST_RSC_CATALOG_CONTROLS_MODULE_ID: &str = "8561";
pub const RUST_RSC_CATALOG_CONTROLS_CHUNKS: &[&str] = &[
    "536",
    "static/chunks/app/catalog/js/page-e3600af0b23c74f8.js",
];
pub const RUST_RSC_LAYOUT_ROUTER_MODULE_ID: &str = "1793";
pub const RUST_RSC_LAYOUT_ROUTER_CHUNKS: &[&str] = &[];
pub const RUST_RSC_TEMPLATE_CONTEXT_MODULE_ID: &str = "9221";
pub const RUST_RSC_TEMPLATE_CONTEXT_CHUNKS: &[&str] = &[];

#[path = "../../app/layout.rs"]
mod component_0;
#[path = "../../app/archive/[[...parts]]/page.rs"]
mod component_1;
#[path = "../../app/dashboard/settings/page.rs"]
mod component_10;
#[path = "../../app/dashboard/@team/settings/page.rs"]
mod component_11;
#[path = "../../app/docs/[...parts]/page.rs"]
mod component_12;
#[path = "../../app/request/page.rs"]
mod component_13;
#[path = "../../app/rust-page/page.rs"]
mod component_14;
#[path = "../../app/search/page.rs"]
mod component_15;
#[path = "../../app/blog/[slug]/layout.rs"]
mod component_2;
#[path = "../../app/blog/[slug]/page.rs"]
mod component_3;
#[path = "../../app/catalog/rust/page.rs"]
mod component_4;
#[path = "../../app/catalog/rust/product/[id]/page.rs"]
mod component_5;
#[path = "../../app/control/[kind]/page.rs"]
mod component_6;
#[path = "../../app/dashboard/layout.rs"]
mod component_7;
#[path = "../../app/dashboard/page.rs"]
mod component_8;
#[path = "../../app/dashboard/@team/page.rs"]
mod component_9;

pub fn render_native_path(
    pathname: &str,
    search_params: &std::collections::BTreeMap<String, ParamValue>,
    request: &RequestData,
) -> Option<RenderResult> {
    if let Some(params) = match_route("/archive/[[...parts]]", pathname) {
        return Some(render_route_0(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/blog/[slug]", pathname) {
        return Some(render_route_1(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/catalog/rust", pathname) {
        return Some(render_route_2(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/catalog/rust/product/[id]", pathname) {
        return Some(render_route_3(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/control/[kind]", pathname) {
        return Some(render_route_4(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/dashboard", pathname) {
        return Some(render_route_5(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/dashboard/settings", pathname) {
        return Some(render_route_6(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/docs/[...parts]", pathname) {
        return Some(render_route_7(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/request", pathname) {
        return Some(render_route_8(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/rust-page", pathname) {
        return Some(render_route_9(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    if let Some(params) = match_route("/search", pathname) {
        return Some(render_route_10(
            params,
            search_params.clone(),
            request.clone(),
        ));
    }
    None
}

pub fn render_native_ppr_segment(
    pathname: &str,
    request_key: &str,
    search_params: &std::collections::BTreeMap<String, ParamValue>,
    request: &RequestData,
) -> Option<RenderResult> {
    if let Some(params) = match_route("/archive/[[...parts]]", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/archive/$oc$parts/__PAGE__" => {
                return Some(component_1::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/archive" => return Some(Ok(crate::next_layout_router("children"))),
            "/archive/$oc$parts" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/blog/[slug]", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/blog/$d$slug" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_2::render(props));
            }
            "/blog/$d$slug/__PAGE__" => {
                return Some(component_3::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/blog" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/catalog/rust", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/catalog/rust/__PAGE__" => {
                return Some(component_4::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/catalog" => return Some(Ok(crate::next_layout_router("children"))),
            "/catalog/rust" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/catalog/rust/product/[id]", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/catalog/rust/product/$d$id/__PAGE__" => {
                return Some(component_5::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/catalog" => return Some(Ok(crate::next_layout_router("children"))),
            "/catalog/rust" => return Some(Ok(crate::next_layout_router("children"))),
            "/catalog/rust/product" => return Some(Ok(crate::next_layout_router("children"))),
            "/catalog/rust/product/$d$id" => {
                return Some(Ok(crate::next_layout_router("children")));
            }
            _ => return None,
        }
    }
    if let Some(params) = match_route("/control/[kind]", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/control/$d$kind/__PAGE__" => {
                return Some(component_6::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/control" => return Some(Ok(crate::next_layout_router("children"))),
            "/control/$d$kind" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/dashboard", pathname) {
        match request_key {
            "/_index" => {
                let mut props =
                    LayoutProps::new(crate::next_layout_router("children"), params.clone())
                        .with_request(request.clone());
                props
                    .slots
                    .insert("team".to_owned(), crate::next_layout_router("team"));
                return Some(component_0::render(props));
            }
            "/dashboard" => {
                let mut props =
                    LayoutProps::new(crate::next_layout_router("children"), params.clone())
                        .with_request(request.clone());
                props
                    .slots
                    .insert("team".to_owned(), crate::next_layout_router("team"));
                return Some(component_7::render(props));
            }
            "/dashboard/__PAGE__" => {
                return Some(component_8::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/dashboard/@team/__PAGE__" => {
                return Some(component_9::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            _ => return None,
        }
    }
    if let Some(params) = match_route("/dashboard/settings", pathname) {
        match request_key {
            "/_index" => {
                let mut props =
                    LayoutProps::new(crate::next_layout_router("children"), params.clone())
                        .with_request(request.clone());
                props
                    .slots
                    .insert("team".to_owned(), crate::next_layout_router("team"));
                return Some(component_0::render(props));
            }
            "/dashboard" => {
                let mut props =
                    LayoutProps::new(crate::next_layout_router("children"), params.clone())
                        .with_request(request.clone());
                props
                    .slots
                    .insert("team".to_owned(), crate::next_layout_router("team"));
                return Some(component_7::render(props));
            }
            "/dashboard/settings/__PAGE__" => {
                return Some(component_10::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/dashboard/@team/settings/__PAGE__" => {
                return Some(component_11::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/dashboard/settings" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/docs/[...parts]", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/docs/$c$parts/__PAGE__" => {
                return Some(component_12::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/docs" => return Some(Ok(crate::next_layout_router("children"))),
            "/docs/$c$parts" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/request", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/request/__PAGE__" => {
                return Some(component_13::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/request" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/rust-page", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/rust-page/__PAGE__" => {
                return Some(component_14::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/rust-page" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    if let Some(params) = match_route("/search", pathname) {
        match request_key {
            "/_index" => {
                let props = LayoutProps::new(crate::next_layout_router("children"), params.clone())
                    .with_request(request.clone());

                return Some(component_0::render(props));
            }
            "/search/__PAGE__" => {
                return Some(component_15::render(
                    PageProps::with_search_params(params.clone(), search_params.clone())
                        .with_request(request.clone()),
                ));
            }
            "/search" => return Some(Ok(crate::next_layout_router("children"))),
            _ => return None,
        }
    }
    None
}

pub fn native_ppr_route_pattern(pathname: &str) -> Option<&'static str> {
    if match_route("/archive/[[...parts]]", pathname).is_some() {
        return Some("/archive/[[...parts]]");
    }
    if match_route("/blog/[slug]", pathname).is_some() {
        return Some("/blog/[slug]");
    }
    if match_route("/catalog/rust", pathname).is_some() {
        return Some("/catalog/rust");
    }
    if match_route("/catalog/rust/product/[id]", pathname).is_some() {
        return Some("/catalog/rust/product/[id]");
    }
    if match_route("/control/[kind]", pathname).is_some() {
        return Some("/control/[kind]");
    }
    if match_route("/dashboard", pathname).is_some() {
        return Some("/dashboard");
    }
    if match_route("/dashboard/settings", pathname).is_some() {
        return Some("/dashboard/settings");
    }
    if match_route("/docs/[...parts]", pathname).is_some() {
        return Some("/docs/[...parts]");
    }
    if match_route("/request", pathname).is_some() {
        return Some("/request");
    }
    if match_route("/rust-page", pathname).is_some() {
        return Some("/rust-page");
    }
    if match_route("/search", pathname).is_some() {
        return Some("/search");
    }
    None
}

pub fn native_parallel_slot_paths(
    pathname: &str,
) -> &'static [(&'static str, &'static str, &'static str)] {
    match pathname {
        "/dashboard" => &[("/dashboard", "team", "")],
        "/dashboard/settings" => &[("/dashboard", "team", "settings")],
        _ => &[],
    }
}

fn render_route_0(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_1::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_1(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_3::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_2::render(layout_props)?;
    }
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_2(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_4::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_3(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_5::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_4(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_6::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_5(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let parallel_slot_0 = component_9::render(
        PageProps::with_search_params(params.clone(), search_params.clone())
            .with_request(request.clone()),
    )?;
    let mut node = component_8::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let mut layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());
        layout_props
            .slots
            .insert("team".to_owned(), parallel_slot_0.clone());
        node = component_7::render(layout_props)?;
    }
    {
        let mut layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());
        layout_props
            .slots
            .insert("team".to_owned(), parallel_slot_0.clone());
        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_6(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let parallel_slot_0 = component_11::render(
        PageProps::with_search_params(params.clone(), search_params.clone())
            .with_request(request.clone()),
    )?;
    let mut node = component_10::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let mut layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());
        layout_props
            .slots
            .insert("team".to_owned(), parallel_slot_0.clone());
        node = component_7::render(layout_props)?;
    }
    {
        let mut layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());
        layout_props
            .slots
            .insert("team".to_owned(), parallel_slot_0.clone());
        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_7(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_12::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_8(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_13::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_9(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_14::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn render_route_10(
    params: Params,
    search_params: std::collections::BTreeMap<String, ParamValue>,
    request: RequestData,
) -> RenderResult {
    let mut node = component_15::render(
        PageProps::with_search_params(params.clone(), search_params).with_request(request.clone()),
    )?;
    {
        let layout_props = LayoutProps::new(node, params.clone()).with_request(request.clone());

        node = component_0::render(layout_props)?;
    }
    Ok(node)
}

fn match_route(pattern: &str, pathname: &str) -> Option<Params> {
    let pattern_segments: Vec<_> = pattern
        .split('/')
        .filter(|value| !value.is_empty())
        .collect();
    let path_segments: Vec<String> = pathname
        .split('/')
        .filter(|value| !value.is_empty())
        .map(percent_decode_path_segment)
        .collect::<Option<_>>()?;
    let mut params = Params::default();
    let mut path_index = 0;

    for segment in pattern_segments {
        if segment.starts_with("[[...") && segment.ends_with("]]") {
            let name = &segment[5..segment.len() - 2];
            let values = path_segments[path_index..].to_vec();
            params.insert(name, ParamValue::Strings(values));
            path_index = path_segments.len();
            break;
        }
        if segment.starts_with("[...") && segment.ends_with(']') {
            if path_index == path_segments.len() {
                return None;
            }
            let name = &segment[4..segment.len() - 1];
            let values = path_segments[path_index..].to_vec();
            params.insert(name, ParamValue::Strings(values));
            path_index = path_segments.len();
            break;
        }
        let value = path_segments.get(path_index)?;
        if segment.starts_with('[') && segment.ends_with(']') {
            params.insert(
                &segment[1..segment.len() - 1],
                ParamValue::String(value.clone()),
            );
        } else if segment != value {
            return None;
        }
        path_index += 1;
    }

    (path_index == path_segments.len()).then_some(params)
}

fn percent_decode_path_segment(value: &str) -> Option<String> {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' {
            let high = hex_value(*bytes.get(index + 1)?)?;
            let low = hex_value(*bytes.get(index + 2)?)?;
            decoded.push((high << 4) | low);
            index += 3;
        } else {
            decoded.push(bytes[index]);
            index += 1;
        }
    }
    String::from_utf8(decoded).ok()
}

fn hex_value(value: u8) -> Option<u8> {
    match value {
        b'0'..=b'9' => Some(value - b'0'),
        b'a'..=b'f' => Some(value - b'a' + 10),
        b'A'..=b'F' => Some(value - b'A' + 10),
        _ => None,
    }
}
