use std::{
    collections::BTreeMap,
    fmt,
    future::Future,
    sync::{Arc, OnceLock},
};

use futures_util::future::BoxFuture;
use next_rs_core::{Error, Result};

use crate::{
    context::RenderContext,
    manifest::{LoaderManifest, LoaderManifestEntry},
};

/// The future returned by a slot loader.
pub type BoxedLoaderFuture = BoxFuture<'static, Result<serde_json::Value>>;

/// A registered `#[react_component]` loader.
///
/// Implementations are generated by the macro; the trait is public so that
/// hand-written loaders and test doubles are possible.
pub trait SlotLoader: Send + Sync + 'static {
    /// Stable identifier recorded in the loader manifest (spec §65).
    fn loader_id(&self) -> &str;

    /// The React Client Component this loader produces props for.
    fn component_id(&self) -> &str;

    /// Number of serialisable arguments after `RenderContext` (spec §29).
    fn arity(&self) -> usize;

    /// Runs the loader with a freshly reconstructed context (spec §59 step 6).
    fn invoke(&self, context: RenderContext, args: Vec<serde_json::Value>) -> BoxedLoaderFuture;
}

/// Adapts a closure into a [`SlotLoader`].
pub struct TypedLoader<F> {
    loader_id: String,
    component_id: String,
    arity: usize,
    invoke: F,
}

impl<F> TypedLoader<F> {
    pub fn new(
        loader_id: impl Into<String>,
        component_id: impl Into<String>,
        arity: usize,
        invoke: F,
    ) -> Self {
        Self {
            loader_id: loader_id.into(),
            component_id: component_id.into(),
            arity,
            invoke,
        }
    }
}

impl<F> fmt::Debug for TypedLoader<F> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TypedLoader")
            .field("loader_id", &self.loader_id)
            .field("component_id", &self.component_id)
            .field("arity", &self.arity)
            .finish()
    }
}

impl<F, Fut> SlotLoader for TypedLoader<F>
where
    F: Fn(RenderContext, Vec<serde_json::Value>) -> Fut + Send + Sync + 'static,
    Fut: Future<Output = Result<serde_json::Value>> + Send + 'static,
{
    fn loader_id(&self) -> &str {
        &self.loader_id
    }

    fn component_id(&self) -> &str {
        &self.component_id
    }

    fn arity(&self) -> usize {
        self.arity
    }

    fn invoke(&self, context: RenderContext, args: Vec<serde_json::Value>) -> BoxedLoaderFuture {
        Box::pin((self.invoke)(context, args))
    }
}

/// The static set of loaders a build exposes (spec §65).
///
/// The refresh endpoint resolves loader IDs *only* through this registry, so
/// arbitrary function names, Rust symbols, deserialisation types and
/// user-selected components can never be invoked.
#[derive(Default, Clone)]
pub struct LoaderRegistry {
    loaders: BTreeMap<String, Arc<dyn SlotLoader>>,
}

static GLOBAL_REGISTRY: OnceLock<LoaderRegistry> = OnceLock::new();

impl LoaderRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers `loader`, rejecting a duplicate ID.
    ///
    /// Two loaders sharing an ID would make invocation ambiguous, which is a
    /// build error rather than something to resolve at runtime.
    pub fn register(&mut self, loader: Arc<dyn SlotLoader>) -> Result<()> {
        let id = loader.loader_id().to_owned();
        if id.is_empty() {
            return Err(Error::internal("loader ID must not be empty"));
        }
        if self.loaders.contains_key(&id) {
            return Err(Error::internal(format!("duplicate loader ID `{id}`")));
        }
        self.loaders.insert(id, loader);
        Ok(())
    }

    /// Builder-style [`LoaderRegistry::register`].
    pub fn with(mut self, loader: Arc<dyn SlotLoader>) -> Result<Self> {
        self.register(loader)?;
        Ok(self)
    }

    pub fn get(&self, loader_id: &str) -> Option<&Arc<dyn SlotLoader>> {
        self.loaders.get(loader_id)
    }

    pub fn contains(&self, loader_id: &str) -> bool {
        self.loaders.contains_key(loader_id)
    }

    pub fn len(&self) -> usize {
        self.loaders.len()
    }

    pub fn is_empty(&self) -> bool {
        self.loaders.is_empty()
    }

    pub fn loader_ids(&self) -> impl Iterator<Item = &str> {
        self.loaders.keys().map(String::as_str)
    }

    /// Resolves a loader, verifying that the caller's expected component matches
    /// the registration.
    ///
    /// Without this check a token or marker could pair a loader with a component
    /// it was never bound to, and the browser would mount the wrong component
    /// with someone else's props.
    pub fn resolve(&self, loader_id: &str, component_id: &str) -> Result<&Arc<dyn SlotLoader>> {
        let loader = self
            .get(loader_id)
            .ok_or_else(|| Error::not_found(format!("unknown loader `{loader_id}`")))?;
        if loader.component_id() != component_id {
            return Err(Error::forbidden(format!(
                "loader `{loader_id}` is bound to component `{}`, not `{component_id}`",
                loader.component_id()
            )));
        }
        Ok(loader)
    }

    /// Resolves and invokes a loader, checking arity first.
    pub async fn invoke(
        &self,
        loader_id: &str,
        component_id: &str,
        context: RenderContext,
        args: Vec<serde_json::Value>,
    ) -> Result<serde_json::Value> {
        let loader = self.resolve(loader_id, component_id)?;
        if args.len() != loader.arity() {
            return Err(Error::bad_request(format!(
                "loader `{loader_id}` expects {} argument(s), got {}",
                loader.arity(),
                args.len()
            )));
        }
        loader.invoke(context, args).await
    }

    /// The manifest written to `.next-rs/manifests/react-loaders.json` (spec §83).
    pub fn manifest(&self, build_id: impl Into<String>) -> LoaderManifest {
        LoaderManifest {
            build_id: build_id.into(),
            protocol_version: next_rs_crypto::PROTOCOL_VERSION,
            loaders: self
                .loaders
                .values()
                .map(|loader| LoaderManifestEntry {
                    id: loader.loader_id().to_owned(),
                    component: loader.component_id().to_owned(),
                    arity: loader.arity(),
                })
                .collect(),
        }
    }

    /// Installs this registry as the process-wide registry.
    ///
    /// Fails if one is already installed: silently replacing the registry would
    /// make which loaders exist depend on start-up ordering.
    pub fn install_global(self) -> Result<()> {
        GLOBAL_REGISTRY
            .set(self)
            .map_err(|_| Error::internal("a global loader registry is already installed"))
    }

    /// The process-wide registry, if installed.
    pub fn global() -> Option<&'static Self> {
        GLOBAL_REGISTRY.get()
    }

    /// The process-wide registry, or an error explaining what is missing.
    pub fn require_global() -> Result<&'static Self> {
        Self::global().ok_or_else(|| {
            Error::internal(
                "no next-rs loader registry is installed; call LoaderRegistry::install_global \
                 during start-up",
            )
        })
    }
}

impl fmt::Debug for LoaderRegistry {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("LoaderRegistry")
            .field("loaders", &self.loaders.keys().collect::<Vec<_>>())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn loader(id: &str, component: &str, arity: usize) -> Arc<dyn SlotLoader> {
        let component = component.to_owned();
        Arc::new(TypedLoader::new(
            id,
            component,
            arity,
            |_ctx, args| async move { Ok(json!({ "args": args })) },
        ))
    }

    fn context() -> RenderContext {
        RenderContext::builder().build()
    }

    #[test]
    fn registers_and_resolves_loaders() {
        let registry = LoaderRegistry::new()
            .with(loader("dashboard", "Dashboard", 1))
            .unwrap()
            .with(loader("metrics", "Metrics", 1))
            .unwrap();

        assert_eq!(registry.len(), 2);
        assert!(registry.contains("dashboard"));
        assert!(registry.resolve("dashboard", "Dashboard").is_ok());
        assert_eq!(
            registry.loader_ids().collect::<Vec<_>>(),
            vec!["dashboard", "metrics"]
        );
    }

    #[test]
    fn rejects_duplicate_and_empty_loader_ids() {
        let mut registry = LoaderRegistry::new();
        registry
            .register(loader("dashboard", "Dashboard", 1))
            .unwrap();
        assert!(registry.register(loader("dashboard", "Other", 1)).is_err());
        assert!(registry.register(loader("", "Dashboard", 0)).is_err());
    }

    #[tokio::test]
    async fn unknown_loaders_are_not_invokable() {
        let registry = LoaderRegistry::new();
        let error = registry
            .invoke("anything", "Dashboard", context(), vec![])
            .await
            .unwrap_err();
        assert_eq!(error.status().as_u16(), 404);
    }

    #[tokio::test]
    async fn a_loader_cannot_be_paired_with_another_component() {
        let registry = LoaderRegistry::new()
            .with(loader("dashboard", "Dashboard", 1))
            .unwrap();
        let error = registry
            .invoke("dashboard", "AdminPanel", context(), vec![json!(1)])
            .await
            .unwrap_err();
        assert_eq!(error.status().as_u16(), 403);
    }

    #[tokio::test]
    async fn arity_is_enforced() {
        let registry = LoaderRegistry::new()
            .with(loader("dashboard", "Dashboard", 2))
            .unwrap();

        let error = registry
            .invoke("dashboard", "Dashboard", context(), vec![json!(1)])
            .await
            .unwrap_err();
        assert_eq!(error.status().as_u16(), 400);
        assert!(error.message().contains("expects 2 argument(s), got 1"));

        assert!(
            registry
                .invoke(
                    "dashboard",
                    "Dashboard",
                    context(),
                    vec![json!(1), json!(2)]
                )
                .await
                .is_ok()
        );
    }

    #[tokio::test]
    async fn invokes_the_loader_with_its_arguments() {
        let registry = LoaderRegistry::new()
            .with(loader("dashboard", "Dashboard", 1))
            .unwrap();
        let props = registry
            .invoke("dashboard", "Dashboard", context(), vec![json!(42)])
            .await
            .unwrap();
        assert_eq!(props, json!({ "args": [42] }));
    }

    #[tokio::test]
    async fn loader_errors_propagate() {
        let failing: Arc<dyn SlotLoader> = Arc::new(TypedLoader::new(
            "boom",
            "Boom",
            0,
            |_ctx, _args| async move { Err(Error::forbidden("nope")) },
        ));
        let registry = LoaderRegistry::new().with(failing).unwrap();
        let error = registry
            .invoke("boom", "Boom", context(), vec![])
            .await
            .unwrap_err();
        assert_eq!(error.status().as_u16(), 403);
    }

    #[test]
    fn produces_a_manifest() {
        let registry = LoaderRegistry::new()
            .with(loader("dashboard", "Dashboard", 1))
            .unwrap();
        let manifest = registry.manifest("build-1");
        assert_eq!(manifest.build_id, "build-1");
        assert_eq!(manifest.loaders.len(), 1);
        assert_eq!(manifest.loaders[0].component, "Dashboard");
        assert_eq!(manifest.loaders[0].arity, 1);
    }

    #[test]
    fn requiring_a_missing_global_registry_explains_itself() {
        // The global registry is process-wide and installed by the runtime; in
        // unit tests it is normally absent.
        if LoaderRegistry::global().is_none() {
            let error = LoaderRegistry::require_global().unwrap_err();
            assert!(error.message().contains("install_global"));
        }
    }

    #[test]
    fn debug_lists_loader_ids() {
        let registry = LoaderRegistry::new()
            .with(loader("dashboard", "Dashboard", 1))
            .unwrap();
        assert!(format!("{registry:?}").contains("dashboard"));
    }
}
