//! The React Client Components this application still uses, and the Rust loaders
//! behind them (§24, §26).
//!
//! Sixteen of `blog-starter`'s components became Rust string templates, because
//! sixteen of them were pure functions of their props with no state, no effects
//! and no event handlers — exactly the components React is *not* needed for.
//!
//! Two are not like that, and both stay React:
//!
//! * **`ThemeSwitcher`** holds state, reads and writes `localStorage`, and subscribes to a
//!   `matchMedia` change event. It mounts client-only: there is nothing useful to server-render,
//!   since its whole output depends on browser state (§37, §38).
//! * **`SubscribeForm`** is server-rendered *and* refreshed from Rust, so this example exercises
//!   all three call-site policies — plain, `.ssr()` and `.swr()` — against the same runtime (§35,
//!   §54).

use next_rs::prelude::*;
use serde::{Deserialize, Serialize};

// Generated by `next-rs build` into `.next-rs/generated/react-bindings.rs` from
// `next-rs.components.ts`; written out here so the example reads end to end.
next_rs::define_component!(ThemeSwitcher);
next_rs::define_component!(SubscribeForm);

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeSwitcherProps {
    /// The key the no-FOUC script and the component agree on.
    pub storage_key: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscribeFormProps {
    pub post_count: usize,
    pub latest_title: String,
}

/// The theme switch. No arguments: the storage key is a build constant.
#[react_component(ThemeSwitcher)]
pub async fn theme_switcher(_ctx: RenderContext) -> Result<ThemeSwitcherProps> {
    Ok(ThemeSwitcherProps {
        storage_key: "nextjs-blog-starter-theme".to_owned(),
    })
}

/// A footer widget whose props come from the same Rust content store the
/// documents are built from.
#[react_component(SubscribeForm)]
pub async fn subscribe_form(_ctx: RenderContext) -> Result<SubscribeFormProps> {
    let posts = crate::content().all().await?;
    Ok(SubscribeFormProps {
        post_count: posts.len(),
        latest_title: posts
            .first()
            .map(|post| post.title.clone())
            .unwrap_or_default(),
    })
}

/// The registry the runtime installs at start-up. Only these loader IDs can ever
/// be invoked through `/__next_rs/react` (§65).
pub fn loaders() -> next_rs::LoaderRegistry {
    next_rs::LoaderRegistry::new()
        .with(theme_switcher_loader())
        .expect("theme_switcher is registered once")
        .with(subscribe_form_loader())
        .expect("subscribe_form is registered once")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_registry_holds_exactly_the_declared_loaders() {
        let registry = loaders();
        assert_eq!(registry.len(), 2);
        assert!(registry.get("theme_switcher").is_some());
        assert!(registry.get("subscribe_form").is_some());
        assert!(registry.get("anything_else").is_none());
    }

    #[test]
    fn a_slot_is_built_without_running_its_loader() {
        // Spec §27: constructing a slot must not touch the loader.
        let slot = theme_switcher();
        let marker = slot.to_string();
        assert!(marker.starts_with("~NRS1."), "{marker}");
    }

    #[tokio::test]
    async fn the_theme_loader_returns_the_storage_key() {
        let props = loaders()
            .invoke(
                "theme_switcher",
                "ThemeSwitcher",
                RenderContext::builder().build(),
                vec![],
            )
            .await
            .unwrap();
        assert_eq!(props["storage_key"], "nextjs-blog-starter-theme");
    }

    #[tokio::test]
    async fn the_subscribe_loader_reads_the_content_store() {
        let props = loaders()
            .invoke(
                "subscribe_form",
                "SubscribeForm",
                RenderContext::builder().build(),
                vec![],
            )
            .await
            .unwrap();
        assert_eq!(props["post_count"], 3);
        assert!(
            props["latest_title"]
                .as_str()
                .is_some_and(|t| !t.is_empty())
        );
    }

    #[tokio::test]
    async fn a_loader_cannot_be_paired_with_another_component() {
        // Spec §65: a loader is bound to the component it was registered against.
        let error = loaders()
            .invoke(
                "theme_switcher",
                "SubscribeForm",
                RenderContext::builder().build(),
                vec![],
            )
            .await
            .unwrap_err();
        assert_eq!(error.code(), "FORBIDDEN");
    }
}
