//! The Node compatibility bridge (spec §3.1, §89).
//!
//! When Rust runs behind Node rather than in the native server, `#[export]`
//! functions are reached through N-API. Everything that has to be *decided* on the
//! Rust side lives here: dispatch through the export registry, JSON argument and
//! return marshalling, an error envelope Node can turn into a rejected Promise, and
//! chunk-by-chunk streaming.
//!
//! The `#[napi]` attribute glue itself is generated by `next-rs build` (spec §82
//! step 10) and is a thin wrapper over [`NapiBridge`], so this crate stays
//! compilable on any target and testable without a Node process.
//!
//! ```ignore
//! // .next-rs/generated/napi.rs
//! #[napi]
//! pub async fn call(name: String, args: String) -> String {
//!     BRIDGE.call_json(&name, &args).await
//! }
//! ```

#![deny(missing_debug_implementations)]

use std::{fmt, sync::Arc};

use futures_util::StreamExt;
use next_rs_core::{Body, Error, ExportRegistry, ExportTarget, Result};

/// Dispatches Node calls into Rust exports.
#[derive(Debug, Clone)]
pub struct NapiBridge {
    exports: Arc<ExportRegistry>,
}

impl NapiBridge {
    pub fn new(exports: Arc<ExportRegistry>) -> Self {
        Self { exports }
    }

    /// Uses the process-wide registry installed at start-up.
    pub fn from_global() -> Result<Self> {
        let exports = ExportRegistry::global().ok_or_else(|| {
            Error::internal(
                "no next-rs export registry is installed; call ExportRegistry::install_global \
                 during start-up",
            )
        })?;
        Ok(Self {
            exports: Arc::new(exports.clone()),
        })
    }

    pub fn exports(&self) -> &Arc<ExportRegistry> {
        &self.exports
    }

    /// Names Node may call, so the generated bindings can be checked against the
    /// build (spec §82 step 8).
    pub fn descriptors(&self) -> Vec<ExportDescriptor> {
        self.exports
            .names()
            .filter_map(|name| self.exports.get(name))
            .map(|export| ExportDescriptor {
                name: export.name().to_owned(),
                js_name: export.js_name().to_owned(),
                arity: export.arity(),
                is_async: export.is_async(),
                browser_compatible: export.target() == ExportTarget::Client,
            })
            .collect()
    }

    /// Calls an export with a JSON array of arguments, returning a JSON envelope.
    ///
    /// This never fails and never panics: Node gets `{"ok":...}` or
    /// `{"error":...}` and turns the latter into a rejected Promise. A panicking
    /// export would otherwise take down the Node process.
    pub async fn call_json(&self, name: &str, args_json: &str) -> String {
        match self.call(name, args_json).await {
            Ok(value) => envelope_ok(&value),
            Err(error) => envelope_error(error.code(), error.public_message()),
        }
    }

    /// Calls an export, surfacing errors as `Result` for Rust callers.
    pub async fn call(&self, name: &str, args_json: &str) -> Result<serde_json::Value> {
        let args = parse_args(args_json)?;
        self.exports.call(name, args).await
    }

    /// Bridges a Rust body to Node as a chunk reader (spec §89 stream bridging).
    pub fn stream(&self, body: Body) -> ChunkReader {
        ChunkReader {
            stream: Some(body.into_stream()),
        }
    }
}

/// What Node needs to know about one export.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportDescriptor {
    pub name: String,
    pub js_name: String,
    pub arity: usize,
    pub is_async: bool,
    pub browser_compatible: bool,
}

/// Reads a streaming body one chunk at a time, for a Node async iterator.
pub struct ChunkReader {
    stream: Option<next_rs_core::BodyStream>,
}

impl fmt::Debug for ChunkReader {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ChunkReader")
            .field("finished", &self.stream.is_none())
            .finish()
    }
}

impl ChunkReader {
    /// Returns the next chunk, or `None` at end of stream.
    pub async fn next_chunk(&mut self) -> Result<Option<Vec<u8>>> {
        let Some(stream) = self.stream.as_mut() else {
            return Ok(None);
        };
        match stream.next().await {
            Some(Ok(chunk)) => Ok(Some(chunk.to_vec())),
            Some(Err(error)) => {
                self.stream = None;
                Err(error)
            }
            None => {
                self.stream = None;
                Ok(None)
            }
        }
    }

    /// True once the stream has been drained or has failed.
    pub fn is_finished(&self) -> bool {
        self.stream.is_none()
    }
}

/// Parses a JSON array of arguments.
fn parse_args(args_json: &str) -> Result<Vec<serde_json::Value>> {
    let trimmed = args_json.trim();
    if trimmed.is_empty() {
        return Ok(Vec::new());
    }
    match serde_json::from_str::<serde_json::Value>(trimmed) {
        Ok(serde_json::Value::Array(values)) => Ok(values),
        Ok(_) => Err(Error::bad_request("export arguments must be a JSON array")),
        Err(error) => Err(Error::bad_request(format!(
            "export arguments are not valid JSON: {error}"
        ))),
    }
}

fn envelope_ok(value: &serde_json::Value) -> String {
    serde_json::json!({ "ok": value }).to_string()
}

fn envelope_error(code: &str, message: &str) -> String {
    serde_json::json!({ "error": { "code": code, "message": message } }).to_string()
}

impl fmt::Display for ExportDescriptor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({} args) as {}", self.name, self.arity, self.js_name)
    }
}

#[cfg(test)]
mod tests {
    use next_rs_core::ExportRegistration;
    use serde_json::json;

    use super::*;

    fn registry() -> Arc<ExportRegistry> {
        Arc::new(
            ExportRegistry::new()
                .with(ExportRegistration::new(
                    "normalize_slug",
                    "normalizeSlug",
                    1,
                    false,
                    ExportTarget::Server,
                    Arc::new(|args| {
                        Box::pin(async move {
                            let value = args[0].as_str().unwrap_or_default();
                            Ok(json!(value.trim().to_lowercase().replace(' ', "-")))
                        })
                    }),
                ))
                .unwrap()
                .with(ExportRegistration::new(
                    "explode",
                    "explode",
                    0,
                    true,
                    ExportTarget::Server,
                    Arc::new(|_| Box::pin(async { Err(Error::internal("dsn=postgres://secret")) })),
                ))
                .unwrap()
                .with(ExportRegistration::new(
                    "fuzzy_search",
                    "fuzzySearch",
                    2,
                    false,
                    ExportTarget::Client,
                    Arc::new(|_| Box::pin(async { Ok(json!([])) })),
                ))
                .unwrap(),
        )
    }

    fn bridge() -> NapiBridge {
        NapiBridge::new(registry())
    }

    #[tokio::test]
    async fn calls_an_export_and_wraps_the_result() {
        let out = bridge()
            .call_json("normalize_slug", r#"["Hello World"]"#)
            .await;
        assert_eq!(out, r#"{"ok":"hello-world"}"#);
    }

    #[tokio::test]
    async fn accepts_an_empty_argument_list() {
        let out = bridge().call_json("explode", "").await;
        assert!(out.contains("\"error\""));
    }

    #[tokio::test]
    async fn redacts_internal_errors_before_they_reach_node() {
        let out = bridge().call_json("explode", "[]").await;
        assert!(out.contains("INTERNAL"));
        assert!(out.contains("internal server error"));
        assert!(!out.contains("postgres"));
    }

    #[tokio::test]
    async fn reports_unknown_exports() {
        let out = bridge().call_json("nope", "[]").await;
        assert!(out.contains("NOT_FOUND"));
    }

    #[tokio::test]
    async fn rejects_malformed_arguments() {
        let out = bridge().call_json("normalize_slug", "not json").await;
        assert!(out.contains("not valid JSON"));

        let out = bridge().call_json("normalize_slug", r#"{"a":1}"#).await;
        assert!(out.contains("must be a JSON array"));
    }

    #[tokio::test]
    async fn enforces_arity_through_the_registry() {
        let out = bridge().call_json("normalize_slug", "[]").await;
        assert!(out.contains("expects 1 argument"));
    }

    #[test]
    fn describes_the_exports_it_can_dispatch() {
        let descriptors = bridge().descriptors();
        assert_eq!(descriptors.len(), 3);

        let fuzzy = descriptors
            .iter()
            .find(|descriptor| descriptor.name == "fuzzy_search")
            .unwrap();
        assert!(fuzzy.browser_compatible);
        assert_eq!(fuzzy.js_name, "fuzzySearch");
        assert_eq!(fuzzy.to_string(), "fuzzy_search(2 args) as fuzzySearch");

        let slug = descriptors
            .iter()
            .find(|descriptor| descriptor.name == "normalize_slug")
            .unwrap();
        assert!(!slug.browser_compatible);
    }

    #[tokio::test]
    async fn bridges_a_streaming_body_chunk_by_chunk() {
        let mut reader = bridge().stream(Body::from_chunks(vec!["ab", "cd"]));
        assert_eq!(reader.next_chunk().await.unwrap(), Some(b"ab".to_vec()));
        assert_eq!(reader.next_chunk().await.unwrap(), Some(b"cd".to_vec()));
        assert_eq!(reader.next_chunk().await.unwrap(), None);
        assert!(reader.is_finished());
        // Draining twice is safe.
        assert_eq!(reader.next_chunk().await.unwrap(), None);
    }

    #[tokio::test]
    async fn a_failing_stream_stops_after_the_error() {
        let body = Body::from_stream(futures_util::stream::iter(vec![
            Ok(bytes::Bytes::from_static(b"ok")),
            Err(Error::internal("boom")),
        ]));
        let mut reader = bridge().stream(body);
        assert_eq!(reader.next_chunk().await.unwrap(), Some(b"ok".to_vec()));
        assert!(reader.next_chunk().await.is_err());
        assert!(reader.is_finished());
        assert_eq!(reader.next_chunk().await.unwrap(), None);
    }

    #[test]
    fn a_missing_global_registry_explains_itself() {
        if ExportRegistry::global().is_none() {
            let error = NapiBridge::from_global().unwrap_err();
            assert!(error.message().contains("install_global"));
        }
    }
}
