//! The typed Rust props loaders behind the example's React slots (spec §26).
//!
//! Each `#[react_component]` produces a public constructor — `account(user_id)` —
//! and a hidden executor registered under the loader ID. Calling the constructor
//! does not run the loader (spec §27).

use next_rs::prelude::*;
use serde::{Deserialize, Serialize};

// Generated by `next-rs build` into `.next-rs/generated/react-bindings.rs` from
// `next-rs.components.ts`; written out here so the example reads end to end.
next_rs::define_component!(Account);
next_rs::define_component!(Metrics);
next_rs::define_component!(Notifications);

#[derive(Debug, Serialize, Deserialize)]
pub struct User {
    pub id: u64,
    pub name: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AccountProps {
    pub user: User,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MetricsProps {
    pub stats: Vec<u64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct NotificationsProps {
    pub items: Vec<String>,
}

#[react_component(Account)]
pub async fn account(ctx: RenderContext, user_id: u64) -> Result<AccountProps> {
    // Authorization runs here, so it runs again on every SWR refresh (spec §61).
    ctx.auth.require_user(user_id).await?;

    Ok(AccountProps {
        user: User {
            id: user_id,
            name: format!("user-{user_id}"),
        },
    })
}

#[react_component(Metrics)]
pub async fn metrics(ctx: RenderContext, org_id: u64) -> Result<MetricsProps> {
    ctx.auth.require_access_to_org(org_id).await?;

    Ok(MetricsProps {
        stats: vec![org_id, org_id * 2, org_id * 3],
    })
}

#[react_component(Notifications)]
pub async fn notifications(ctx: RenderContext, user_id: u64) -> Result<NotificationsProps> {
    ctx.auth.require_user(user_id).await?;

    Ok(NotificationsProps {
        items: vec![format!("hello user {user_id}")],
    })
}

/// The registry the runtime installs at start-up. Only these loader IDs can ever
/// be invoked through `/__next_rs/react` (spec §65).
pub fn loaders() -> next_rs::LoaderRegistry {
    next_rs::LoaderRegistry::new()
        .with(account_loader())
        .expect("account is registered once")
        .with(metrics_loader())
        .expect("metrics is registered once")
        .with(notifications_loader())
        .expect("notifications is registered once")
}
