[package]
name = "next-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A progressive Rust runtime for Next.js"

[dependencies]
futures-util = { workspace = true }
next-rs-core = { workspace = true }
next-rs-crypto = { workspace = true }
next-rs-html = { workspace = true }
next-rs-http = { workspace = true }
next-rs-macros = { workspace = true }
next-rs-react = { workspace = true }
next-rs-router = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
